# Generated by Django 3.1.4 on 2020-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_or_no', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=10)),
                ('sad_or_happy', models.CharField(choices=[('s', 'Sad'), ('h', 'Happy')], max_length=10)),
                ('tired_or_not', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=10)),
                ('alone_or_not', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=10)),
            ],
        ),
    ]
