# Generated by Django 3.1.4 on 2020-12-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_remove_mood_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
